Add CORS exception for tutorial.ponylang.io to rout /evaluate.json
ponylang/pony-playground pull request #212
Opened 2024-04-30 08:37 UTC by shaedrich

As discussed in #205

2024-05-14 18:19 UTC, jemc commented
Looks good to me. I can approve after it's no longer a draft.

2024-05-25 05:36 UTC, jemc approved these changes

2024-05-25 05:41 UTC, jemc commented on src/api.rs
> +let layer = CorsLayer::new().allow_origin(
Looks like the linter wants this change:
```suggestion
const layer = CorsLayer::new().allow_origin(
```

2024-05-31 18:15 UTC, jemc commented
Looks like there's a parsing issue in the CI failure.

2024-06-04 18:01 UTC, shaedrich commented
It's fixed now.

2024-06-12 03:32 UTC, shaedrich commented
Done

2024-06-25 18:40 UTC, SeanTAllen commented
@mfelsche do you know what needs to happen for this?

2024-06-26 07:55 UTC, mfelsche requested changes
This still needs a dependency on `tower_http` added to `Cargo.toml` like so:

```toml
tower-http = { version = "0.5", features = ["cors"] }
```

2024-06-30 11:26 UTC, shaedrich commented on src/api.rs
> +const layer: CorsLayer = CorsLayer::new().allow_origin(
Done

2024-06-30 12:54 UTC, mfelsche approved these changes
LGTM

2024-06-30 12:57 UTC, merged

2024-06-30 14:44 UTC, mfelsche commented
@shaedrich this is live now on https://playground.ponylang.io

2024-06-30 15:07 UTC, shaedrich commented
Cool, thanks for deploying!